Repository FC-DEV2-FinalProject/unicat-ui, pull requests merged in 2025-03, with the labels that each got.

#17 [⚙️ Chore] 폴더 구조 재정의 및 api. page 이동
  app/page.tsx
  src/app/api/auth/route.ts
  src/app/apis/.gitkeep
  src/app/layout.tsx
  src/app/page.tsx
Labels: ⚙️ chore

#23 [⚙️ Chore] 인증서 환경변수 분리 및 next를 위해 재설정
  .gitignore
Labels: ⚙️ chore

#34 [🎨 UI/UX] 로그인 페이지
  public/images/Google.svg
  public/images/Kakao.svg
  public/images/login-background.png
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/login/page.tsx
  src/styles/globals.css
Labels: 🚀 feature

#37 [🎨 UI/UX] 회원가입 페이지
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/sign-up/page.tsx
Labels: 🎨 ui/ux

#42 [🐞 Bug] tailwind를 전체 레이아웃에 적용
  src/app/(home)/layout.tsx
  src/app/layout.tsx
Labels: 🐞 bug

#43 [🎨 UI/UX] 전체 대시보드 페이지 UI 구현
  src/app/(home)/dashboard/page.tsx
Labels: 🎨 ui/ux

#54 [🚀 Feature] 소셜 로그인 기능 구현
  package.json
  src/app/(auth)/login/callback/page.tsx
  src/app/(auth)/login/components/SocialLoginButton.tsx
  src/app/(auth)/login/page.tsx
Labels: 🚀 feature

#57 [⚡ Hotfix] API 호출을 위한 baseURL 변경
  src/utils/apiClient.ts
Labels: ⚡ hotfix

#55 [🚀 Feature] 일반 회원가입 기능 구현
  src/app/(auth)/sign-up/page.tsx
  src/types/signUpTypes.ts
Labels: 🚀 feature

#66 [🚀 Feature] 전체 대시보드 기능
  src/app/(home)/dashboard/page.tsx
  src/mocks/data/dashboard.ts
  src/mocks/data/index.ts
  src/mocks/handlers.ts
  src/types/DashboardTypes.ts
Labels: 🚀 feature
